### ISSUE TITLE
getting error when attempting to package file

### ISSUE THREAD

**Issue by awright424** [Jorl17/jar2app#11]
jar2app UserProxy.jar test -r jre1.8.0_111.jre/
Packing UserProxy.jar into /Users/macmini/Desktop/shit to sign/jartest/test.app
Traceback (most recent call last):
  File "/usr/local/bin/jar2app", line 487, in <module>
    main()
  File "/usr/local/bin/jar2app", line 485, in main
    make_app(*parse_input())
  File "/usr/local/bin/jar2app", line 434, in make_app
    copy_base_files(app_full_path, icon, jar_file, jdk, jdk_isfile)
  File "/usr/local/bin/jar2app", line 300, in copy_base_files
    copy_jdk(app_full_path, jdk, jdk_isfile)
  File "/usr/local/bin/jar2app", line 275, in copy_jdk
    shutil.copytree(jdk, os.path.join(app_full_path, 'Contents', 'PlugIns', os.path.basename(jdk)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: './test.app/Contents/PlugIns/'

**Comment by Jorl17** [comment]
Hi. I'll look into this later today, thanks for the report!

Did this happen on the first run of the application or did you run it multiple times? It seems like this JDK was already in the .app folder, and so `copytree`failed with a "File Exists "error which we can easily fix

**Comment by awright424** [comment]
I removed the folder and made sure existing files were removed but get that error when attempting to specify the jre

**Comment by Jorl17** [comment]
Thanks for your feedback. I look into this when I get home (in ~7 hours)

**Comment by Jorl17** [comment]
I have not forgotten about this, I just lacked time today. When I have the time I'll post back with results

**Comment by Jorl17** [comment]
This issue should be fixed by commit 	c8c53cd. Do tell me if it's not and once again thanks for your report!
